-- SCRIPT PARA GERAÇÃO DA ESTRUTURA DO BANCO DO PROJETO SOCIALL (MySQL)
-- Alan Vival Martins, Roberto Pires Neto e André Gobbi

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
create schema if not exists uvv_poo2_sociall;
use uvv_poo2_sociall;

-- -----------------------------------------------------
-- Tabelas
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS PREFERENCIA_TIPO (
	ID SMALLINT(4) NOT NULL AUTO_INCREMENT,
    DESCRICAO VARCHAR(100) NOT NULL,
    
    PRIMARY KEY (ID),
    UNIQUE INDEX DESCRICAO_UNIQUE (DESCRICAO ASC)
);

CREATE TABLE IF NOT EXISTS USUARIO (
	ID SMALLINT(4) NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(200) NOT NULL,
    SENHA VARCHAR(200) NOT NULL,
    ENDERECO VARCHAR(250) NOT NULL,
    
    PRIMARY KEY (ID),
    UNIQUE INDEX EMAIL_UNIQUE (EMAIL ASC)
);

CREATE TABLE IF NOT EXISTS PREFERENCIA_USUARIO (
	ID SMALLINT(4) NOT NULL AUTO_INCREMENT, 
	USUARIO_ID SMALLINT(4) NOT NULL,
    PREFERENCIA_ID SMALLINT(4) NOT NULL,
    
    PRIMARY KEY (ID),
    UNIQUE KEY uk_USUARIO_PREFERENCIA (USUARIO_ID, PREFERENCIA_ID),
	INDEX fk_PREFERENCIA_USUARIO_USUARIO_idx (USUARIO_ID),
	INDEX fk_PREFERENCIA_USUARIO_PREFERENCIA_idx (PREFERENCIA_ID),
	CONSTRAINT fk_PREFERENCIA_USUARIO_USUARIO
		FOREIGN KEY (USUARIO_ID)
		REFERENCES USUARIO (ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
	CONSTRAINT fk_PREFERENCIA_USUARIO_PREFERENCIA
		FOREIGN KEY (PREFERENCIA_ID)
		REFERENCES PREFERENCIA_TIPO (ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS HOBBIE_USUARIO (
	ID SMALLINT(4) NOT NULL AUTO_INCREMENT,
    USUARIO_ID SMALLINT(4) NOT NULL,
    DESCRICAO VARCHAR(150) NOT NULL,
    
    PRIMARY KEY (ID),
    INDEX fk_HOBBIE_USUARIO_USUARIO_idx (USUARIO_ID ASC),
	CONSTRAINT fk_HOBBIE_USUARIO_USUARIO
		FOREIGN KEY (USUARIO_ID)
		REFERENCES USUARIO (ID),
	CONSTRAINT uk_HOBBIE_USUARIO_DESCRICAO UNIQUE (USUARIO_ID, DESCRICAO)
);

CREATE TABLE IF NOT EXISTS EVENTO (
	ID SMALLINT(4) NOT NULL AUTO_INCREMENT,
    USUARIO_ID SMALLINT(4) NOT NULL,
    NOME VARCHAR(150) NOT NULL,
    DATA DATE,
    DESCRICAO VARCHAR(100) NOT NULL,
    STATUS BOOL DEFAULT 1,
    FOTO VARCHAR(200) NOT NULL,
    ENDERECO VARCHAR(250) NOT NULL,
    MAXIMO_INSCRITOS SMALLINT(4) NOT NULL,
	
    PRIMARY KEY (ID),
    INDEX fk_EVENTO_USUARIO_CRIADOR_idx (USUARIO_ID ASC),
    CONSTRAINT fk_EVENTO_USUARIO_CRIADOR
		FOREIGN KEY (USUARIO_ID)
        REFERENCES USUARIO (ID)
);

CREATE TABLE IF NOT EXISTS PREFERENCIA_EVENTO (
	ID SMALLINT(4) NOT NULL AUTO_INCREMENT, 
	EVENTO_ID SMALLINT(4) NOT NULL,
    PREFERENCIA_ID SMALLINT(4) NOT NULL,
    
    PRIMARY KEY (ID),
    UNIQUE KEY uk_EVENTO_PREFERENCIA (EVENTO_ID, PREFERENCIA_ID),
	INDEX fk_PREFERENCIA_EVENTO_EVENTO_idx (EVENTO_ID),
	INDEX fk_PREFERENCIA_EVENTO_PREFERENCIA_idx (PREFERENCIA_ID),
	CONSTRAINT fk_PREFERENCIA_EVENTO_EVENTO
		FOREIGN KEY (EVENTO_ID)
		REFERENCES EVENTO (ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
	CONSTRAINT fk_PREFERENCIA_EVENTO_PREFERENCIA
		FOREIGN KEY (PREFERENCIA_ID)
		REFERENCES PREFERENCIA_TIPO (ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS INSCRICAO (
	USUARIO_ID SMALLINT(4) NOT NULL,
    EVENTO_ID SMALLINT(4) NOT NULL,
    STATUS BOOL DEFAULT 1,
    DATA_INSCRICAO DATE,
    
    PRIMARY KEY (USUARIO_ID, EVENTO_ID),
		INDEX fk_INSCRICAO_USUARIO_idx (USUARIO_ID ASC),
		INDEX fk_ISCRICAO_EVENTO_idx (EVENTO_ID ASC),
	CONSTRAINT fk_INSCRICAO_USUARIO
		FOREIGN KEY (USUARIO_ID)
		REFERENCES USUARIO (ID),
	CONSTRAINT fk_ISCRICAO_EVENTO
		FOREIGN KEY (EVENTO_ID)
		REFERENCES EVENTO (ID)
);

-- INSERTS
INSERT INTO PREFERENCIA_TIPO (DESCRICAO) VALUES ('Futebol');
INSERT INTO PREFERENCIA_TIPO (DESCRICAO) VALUES ('Jogos');
INSERT INTO PREFERENCIA_TIPO (DESCRICAO) VALUES ('Filmes');
INSERT INTO PREFERENCIA_TIPO (DESCRICAO) VALUES ('Praias');
INSERT INTO PREFERENCIA_TIPO (DESCRICAO) VALUES ('Comida');
INSERT INTO PREFERENCIA_TIPO (DESCRICAO) VALUES ('Musica');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;